"""add facailities column hashed password

Revision ID: fdf15e8d6051
Revises: 0cb2c156f634
Create Date: 2025-09-16 17:02:27.298796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdf15e8d6051"
down_revision: Union[str, Sequence[str], None] = "0cb2c156f634"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("facilities", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facilities",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
